config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails do
    resources :doses, only: [:show, :new, :create]
    resources :reviews, only: [:show, :new, :create]
  end
  resources :doses, only: [:edit, :update, :destroy]
  resources :reviews, only: [:edit, :update, :destroy]

  root to:'cocktails#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses
  has_many :ingredients, through: :doses
  has_many :reviews, dependent: :destroy
  mount_uploader :photo, PhotoUploader
  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  # validates :ingredient, presence: true
  # validates :cocktail, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, uniqueness: true, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
  validates :rating, inclusion: { in: [1, 2, 3, 4, 5] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      redirect_to new_cocktail_path
    end
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    @cocktail.update(cocktail_params)
    redirect_to cocktail_path(@cocktail)
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :description, :servings, :ingredients, :doses, :reviews, :photo, :instructions, :contributor)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = Cocktail.find(params[:cocktail_id])
    if @dose.save
      redirect_to cocktail_path(@dose.cocktail)
    else
      redirect_to new_cocktail_dose_path
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:ingredient_id, :amount, :method, :cocktail_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.cocktail = Cocktail.find(params[:cocktail_id])
    if @review.save
      redirect_to cocktails_path
    else
      redirect_to new_cocktail_review_path
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/edit.html.erb
<div class="wrapper">
  <div class="container">
    <div class="vertical-pic">
      <div class="flex-item vertical-form">
        <h1>Edit Cocktail <%= @cocktail.name %> </h1>

        <%= simple_form_for(@cocktail) do |f| %>
          <div class="form-group">
            <%= f.input :photo %>
            <%= f.input :photo_cache, as: :hidden, class: 'form-control btn btn-primary' %>
          </div>

          <div class="form-group">
            <%= f.input :name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.input :description, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.input :contributor, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.input :servings, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.input :instructions, class: 'form-control' %>
          </div>

          <ul class="list-inline">
            <li class="list-inline-item">
              <%= f.submit class: 'btn btn-primary' %>
            </li>
            <li class="list-inline-item">
              <%= link_to "Back to All Cocktails", cocktails_path, class: "btn btn-primary"%>
            </li>
          </ul>
        <% end %>
      </div>
        <%= cl_image_tag "https://res.cloudinary.com/diu66bbfw/image/upload/v1550152748/grapefruitfrom2.jpg", class:"vertical" %>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/index.html.erb
<div class="wrapper-home">
  <div class="container">
    <div class="intro">
      <h1>An Ode to the Grapefruit</h1>
      <p class="welcome">
        Grapefruit has long been recognized as an amazing cocktail mixer. The bitter and tart flavors cut through strong alcohol, much like pickle juice. These pink and yellow gems add a touch of sweetness, but are never overwhelming, so this sweet citrus melody will pair well with nearly any bottle you have hiding under that cupboard. Oh, and grapefruits are full of antioxidants and vitamins, so you can feel a little less guilty about drinking so much!
      </p>
      <ul class="list-inline product-controls">
        <li><a href="https://www.facebook.com/"><i class="fab fa-facebook-f"></i></a></s></li>
        <li><a href="https://www.instagram.com/"><i class="fab fa-instagram"></i></a></s></li>
        <li><a href="https://twitter.com/"><i class="fab fa-twitter"></i></a></s></li>
      </ul>
      <h2>Get Ready to Shake Shake Shake</h2>
    </div>
  </div>
</div>

<div class="container">
  <div class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-100" <%= cl_image_tag("https://res.cloudinary.com/diu66bbfw/image/upload/v1550146071/orangegrapefruit.jpg") %> alt="First slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" <%= cl_image_tag("https://res.cloudinary.com/diu66bbfw/image/upload/v1550146070/bluesmoke.jpg") %> alt="Second slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" <%= cl_image_tag("https://res.cloudinary.com/diu66bbfw/image/upload/v1550146071/pinkgrapefruit.jpg") %> alt="Third slide">
      </div>
    </div>
  </div>
</div>

<div class="container">
  <h1 class="text-center">The Menu</h1>
    <div class="row card-group">
        <% @cocktails.each do |cocktail| %>
        <div class="col-4">
            <div class="card-body">
              <h2 class="card-title"> <%= link_to cocktail.name, cocktail_path(cocktail), class: "link" %> </h2>
              <p class="card-text"> <%= cocktail.description %> </p>
              <p> Average rating: <%= cocktail.reviews.average(:rating).round(2) if cocktail.reviews.average(:rating) %> </p>
              <%= link_to "full recipe", cocktail_path(cocktail), class: "link-two"%>
            </div>
          </div>
        <% end %>
    </div>
  <%= link_to "Add New Cocktail", new_cocktail_path, class: "btn btn-primary"%>
</div>

app/views/cocktails/new.html.erb
<div class="wrapper">
  <div class="container">

    <ul class= "list-inline">
      <li class= "list-inline-item">
        <h1>Add Cocktail</h1>
      </li>
      <li class= "list-inline-item">
        <%= link_to "Back to Cocktail List", cocktails_path, class: "btn btn-primary"%>
      </li>
    </ul>
    <div class="vertical-pic">
      <div class="flex-item vertical-form">
        <%= simple_form_for(@cocktail) do |f| %>
          <div class="form-group">
            <%= f.input :photo %>
            <%= f.input :photo_cache, as: :hidden, class: 'form-control btn btn-primary' %>
          </div>

          <div class="form-group">
            <%= f.input :name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.input :contributor, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.input :description, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.input :servings, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.input :instructions, class: 'form-control' %>
          </div>

          <%= f.submit class: 'btn btn-primary' %>
        <% end %>
      </div>
      <div class="flex-item"></div>
        <%= cl_image_tag "https://res.cloudinary.com/diu66bbfw/image/upload/v1550152006/grapefruitform.jpg", class:"vertical" %>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="wrapper">
  <div class="container">
    <div class="vertical-pic">
      <div class="flex-item vertical-form">
        <h1><%= @cocktail.name %></h1>
        <p>Serves: <%= @cocktail.servings %></p>
        <p>Contributor: <%= @cocktail.contributor %></p>
        <p>Why you should try this cocktail: <%= @cocktail.description %></p>

        <h2>Here's what you need to do to make it: </h2>
          <% @cocktail.doses.each do |amt| %>
            <ul>
              <li>
                <%= amt.amount %> - <%= amt.method %> of <%= amt.ingredient.name %>
                <%= link_to '', dose_path(amt), method: :delete, class: "fas fa-trash-alt" %>
              </li>
            </ul>
          <% end %>

        <h2> Now the Instructions: </h2>
        <p> <%= @cocktail.instructions %> </p>
      </div>
      <div class="flex-item">
          <%= cl_image_tag @cocktail.photo, class:"cocktail-image" %>
      </div>
    </div>

    <h2>You Tell Us: How did it taste?</h2>

    <table class="table">
      <% @cocktail.reviews.each do |comment| %>
        <tr>
            <td> <%= comment.content %> </td>
            <td> <%= comment.rating %></td>
        </tr>
      <% end %>
    </table>

    <ul class="list-inline">
      <li class="list-inline-item">
        <%= link_to "Review this Cocktail", new_cocktail_review_path(@cocktail), class: "btn btn-primary"%>
      </li>
      <li class="list-inline-item">
        <%= link_to "Back to Cocktail List", cocktails_path, class: "btn btn-primary"%>
      </li>
     <li class="list-inline-item">
        <%= link_to "Edit this Cocktail", edit_cocktail_path, class: "btn btn-primary"%>
      </li>
      <li class="list-inline-item">
        <%= link_to "Add a Dose to the Cocktail", new_cocktail_dose_path(@cocktail), class: "btn btn-primary"%>
    </ul>
  </div>
</div>

app/views/doses/new.html.erb
<div class="wrapper">
  <div class="container">
    <ul class= "list-inline">
      <li class= "list-inline-item">
        <h2>Add Cocktail</h2>
      </li>
      <li class= "list-inline-item">
        <%= link_to "Back to Cocktail List", cocktails_path, class: "btn btn-primary"%>
      </li>
    </ul>

    <%= simple_form_for [@cocktail, @dose] do |f| %>
      <div class="form-group">
        <%= f.input :amount, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.input :method, class: 'form-control' %>
      </div>

        <div class="form-group">
        <%= f.association :ingredient, collection: Ingredient.all, class: 'form-control' %>
      </div>

      <%= f.submit class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel='icon' href='/assets/ggf.ico?v=2' type='image/x-icon'/ >
  </head>

  <body>
    <div class="navbar-wagon">
      <ul class="list-inline">
        <li class="list-inline-item">
          <%= link_to "Home", cocktails_path, class: "nav-link active"%>
        </li>
        <li class="list-inline-item">
          <%= link_to "Add Cocktail", new_cocktail_path, class: "nav-link active"%>
        </li>
      </ul>
    </div>
    <div class="container">
      <div class="banner">
        <h1 class="banner-title text-center">The Great Grapefruit Cocktail List</h1>
      </div>
    </div>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/reviews/new.html.erb
<div class="wrapper">
  <div class="container">
    <ul class= "list-inline">
      <li class= "list-inline-item">
        <h1>Add Review <%= @cocktail.name %></h1>
      </li>
      <li class= "list-inline-item">
        <%= link_to "Back to Cocktail List", cocktails_path, class: "btn btn-primary"%>
      </li>
    </ul>

    <%= form_for [@cocktail, @review] do |f| %>
      <div class="form-group">
        <%= f.label :content %>
        <%= f.text_field :content, placeholder: "So... what did you think of this lovely libation?", class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :rating %>
        <%= f.text_field :rating, placeholder: "On a scale of 1-5", class: 'form-control' %>
      </div>
      <%= f.submit "Add Review", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>